### ISSUE TITLE
App not downloading from Microsoft store

### ISSUE THREAD

**Issue by Glaecier** [Levminer/screentime#10]
Greetings!
On the lookout for an app that tracks screen time on Windows 11, I came across yours. 
It was exactly what I was looking for, so I tried to install it. However, I received an error (shown in the screenshot).
![Microsoft Store 14-01-2024 09_08_29 AM](https://github.com/Levminer/screentime/assets/156559736/a4670e0c-d00e-4ad9-b59b-0fdfb306f9a3)

Requesting your aid on this issue. 
Thanks!

Edit: I forgot to mention this, the error code is→Code: 0x80190193

**Comment by Levminer** [comment]
Hi!

Did you try to install it from GitHub? https://github.com/Levminer/screentime/releases/download/1.2.1/screentime-1.2.1-windows-x64-installer.exe

**Comment by Glaecier** [comment]
It worked! 
This is perhaps the cleanest UI I have ever seen on a productivity app. I sincerely appreciate the swift response!

Thanks again :D
