### ISSUE TITLE
Windows installer doesn't work

### ISSUE THREAD

**Issue by amirzak** [Levminer/screentime#12]
I downloaded the installer from https://github.com/Levminer/screentime/releases/download/1.2.1/screentime-1.2.1-windows-x64-installer.exe .

First time the wizard opened and i just hit next-next... but the app wasn't installed.
I tried to run the installer one more time but it didn't open...

I will appreciate any assistance.
My machine is running Windows 11 Home 23H2 x64 Intel(R) Core(TM) i7-8550U CPU 16 GB Ram

**Comment by Levminer** [comment]
Try the new version: https://github.com/Levminer/screentime/releases/download/1.2.2/screentime-1.2.2-windows-x64-installer.exe
