### ISSUE TITLE
Taskbar icon

### ISSUE THREAD

**Issue by Leosacha** [Levminer/screentime#6]
Is it possible to view the daily screen time with a taskbar icon - so without open the window ? Or just by placing the mouse on the icon ?
For exemple, I use on my phone this app (https://github.com/markusfisch/ScreenTime). It shows me permanently my daily screen time.
Thank you for all you've done !

**Comment by Levminer** [comment]
![image](https://user-images.githubusercontent.com/33373714/215265421-9284a683-5ffb-4e56-87fd-0d2a89615ef5.png)

Are you thinking about something like this?

**Comment by Leosacha** [comment]
This is really great !

**Comment by Leosacha** [comment]
Is it too complexe to display the screen time directly ? Like measures displayed by the CoreTemp app, that shows me the temperature of my processor.
![Capture d’écran 2023-01-28 140650](https://user-images.githubusercontent.com/123809520/215268633-4eac1416-934d-4f59-ac7d-e023d430af97.jpg)

**Comment by Levminer** [comment]
> Is it too complexe to display the screen time directly ? Like measures displayed by the CoreTemp app, that shows me the temperature of my processor. I don't know if you can put the daily screen time next to the icon of your app, or by replacing the icon to only see the time. ![Capture d’écran 2023-01-28 140650](https://user-images.githubusercontent.com/123809520/215268633-4eac1416-934d-4f59-ac7d-e023d430af97.jpg)

It's not impossible, but kind of complicated. I went with my option, I will publish an update soon.

![image](https://user-images.githubusercontent.com/33373714/215294312-14ab8327-e8fe-48ad-8330-cf139484c2a3.png)

**Comment by Leosacha** [comment]
Thank you for your job ! I will share your app around me.
